### PR TITLE
Add bors

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This adds [bors](https://bors.tech).

---

What you'd need to do: Go to https://bors.tech, add this repository (if you haven't done yet) and ensure the settings from [this comment](https://github.com/philippkeller/rexpect/issues/43#issuecomment-1242939795).

### CODE REVIEW

**Comment by philippkeller** [comment]
@matthiasbeyer I just added bors through https://github.com/apps/bors/installations/new - is there something more I need to do?

**Comment by matthiasbeyer** [comment]
Lets see whether bors knows of this repository... :wink: 

bors ping

**Comment by matthiasbeyer** [comment]
Nice. So yes, you'd need to ensure the settings [I listed in this comment](https://github.com/philippkeller/rexpect/issues/43#issuecomment-1242939795)!

**Comment by philippkeller** [comment]
- Disable squash merges (not required for bors per se, but anyways a good option) ✅ 
- With "Require a pull request before merging" ✅ 
- With "Require status checks to pass before merging" ✅ 
-  With "bors" as only required status check -> waiting until you configured bors
- "Require pull request reviews before merging" MUST be unmarked -> didn't find this setting, is it called "Require review from Code Owners" ?
- Required for administrators as well ✅

**Review by petreeftime — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
Awesome.

So lets see whether bors can merge this. I doubt it right now, as actions seems not to run yet. I had this problem before, and I know how to resolve it. Give me a few minutes!

bors merge

**Comment by matthiasbeyer** [comment]
I messed this up a bit. Bors already merged it.

**Comment by matthiasbeyer** [comment]
> "Require pull request reviews before merging" MUST be unmarked -> didn't find this setting, is it called "Require review from Code Owners" ?

Yes, I think so.

**Pull request closed without merging**
