### PR TITLE
Remove lockfile

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@philippkeller it seems that reviews are required. Can you please disable them? This setting can be managed automatically by bors, if you want to keep this setting (I can file a PR for enabling this with bors)!

**Review by petreeftime — APPROVED** [review]

**Comment by philippkeller** [comment]
@matthiasbeyer sorry, didn't see this before. I don't see where I can disable this?
image
image

**Comment by matthiasbeyer** [comment]
It's the "require approvals" setting.

**Comment by matthiasbeyer** [comment]
bors single on
bors merge

**Comment by matthiasbeyer** [comment]
@philippkeller Just to make sure you do not miss this: This PR was merged, but the setting is still not disabled.

**Comment by philippkeller** [comment]
@matthiasbeyer I just changed the setting now, can you check again? Thanks so much for everything. This project has never been so active ever 🎉

**Comment by matthiasbeyer** [comment]
@philippkeller yes looks alright now. Thanks a lot!

**Pull request merged**
